version: '3'

services:
  users-api:
    container_name: "users-api"
    depends_on:
      - users-db
    image: ghcr.io/matigayito/jjusers:main
    ports:
      - 8080:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: user-db
      DB_HOST: postgres_db
      DB_PORT: 5432

  users-db:
    container_name: users_postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-db

  post-api:
    container_name: "post-api"
    depends_on:
      - post-db
    image: ghcr.io/matigayito/jjposts:main
    ports:
      - 8081:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: post-db
      DB_HOST: postgres_db
      DB_PORT: 5432

  post-db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post-db

  keycloakdb:
    container_name: db_keycloak
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak-db

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db_keycloak
      DB_DATABASE: keycloak-db
      DB_USER: sa
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8082:8080
    depends_on:
      - keycloakdb
